/* Generated by Together */

package com.css.sword.platform.comm.filetemplet.ruler;

import com.css.sword.platform.comm.filetemplet.ITempFile;

public class DefaultStringRulerMap extends AbsStringRuler {
    public Object make(ITempFile tempfile) {
        return "";
    }
}
