var SwordForm$Layout = {
    deflayer:{
        cols:2,
        item:{
            trs:[
                [
                    {name:'caption'},
                    {name:'name'}
                ]
            ]
        }
    },
    layer0:{
        cols:1,
        item:{
            trs:[
                [
                    {name:'caption'},
                    {name:'name'}
                ]
            ]
        }
    },
    layer1:{
        cols:2,
        item:{
            trs:[
                [
                    {name:'caption'},
                    {name:'name'}
                ]
            ]
        }
    },
    layer2:{
        cols:3,
        item:{
            trs:[
                [
                    {name:'caption'},
                    {name:'name'}
                ]
            ]
        }
    },
    layer3:{
        cols:1,
        item:{
            trs:[
                [
                    {name:'caption'},
                    {name:'name'},
                    {name:"des"}
                ]
            ]
        }
    },
    layer4:{
        cols:2,
        item:{
            trs:[
                [
                    {name:'caption'},
                    {name:'name'},
                    {name:"des"}
                ]
            ]
        }
    }

};

